<!DOCTYPE html>
<html lang="en-us">
    <head>
        

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Project 2</title>
        
        <style>

    html body {
        font-family: 'Roboto Slab', sans-serif;
        background-color: white;
    }

    :root {
        --accent: blue;
        --border-width:  5px ;
    }

</style>


<link rel="stylesheet" href="/css/main.css">





<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto%20Slab">


 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css"> 


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
 

    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/go.min.js"></script>
    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/haskell.min.js"></script>
    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/kotlin.min.js"></script>
    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/scala.min.js"></script>
    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/swift.min.js"></script>
    
    <script>hljs.initHighlightingOnLoad();</script>






<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<script>$(document).on('click', function() { $('.collapse').collapse('hide'); })</script>
 <meta name="generator" content="Hugo 0.60.1" />
        

        

        
            <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
        

        

    </head>

    <body>
        

        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand visible-xs" href="#">Project 2</a>
                    <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    
                        <ul class="nav navbar-nav">
                            
                                <li><a href="/">Home</a></li>
                            
                                <li><a href="https://annwang.netlify.com/">Resume Page</a></li>
                            
                                <li><a href="/project1/">Project 1</a></li>
                            
                                <li><a href="/project2/">Project 2</a></li>
                            
                                <li><a href="/2019-12-07-interesting-in-python/">Blog Post</a></li>
                            
                        </ul>
                    
                    
                        <ul class="nav navbar-nav navbar-right">
                            
                                <li class="navbar-icon"><a href="mailto:ann.wang@utexas.edu"><i class="fa fa-envelope-o"></i></a></li>
                            
                                <li class="navbar-icon"><a href="https://github.com/ann-DIY/"><i class="fa fa-github"></i></a></li>
                            
                                <li class="navbar-icon"><a href="https://www.linkedin.com/in/ann-wang-aw29983/"><i class="fa fa-linkedin"></i></a></li>
                            
                        </ul>
                    
                </div>
            </div>
        </nav>


<main>

    <div>
        <h2>Project 2</h2>
        <h5></h5>
        

    </div>

    <div align="start" class="content">


<div id="ann-wang-aw29983" class="section level2">
<h2>Ann Wang, aw29983</h2>
<hr />
<div id="introduction" class="section level4">
<h4>Introduction:</h4>
<p>This is the ‘meteorites’ dataset, which is a dataset containing information about meteorites and where they fell. This dataset was obtained from the Meteoritical Society by NASA. It contains the variables: name, id, name_type, class, mass, fall, year, lat, long, and geolocation of the meteorites.</p>
<div id="manova-testing" class="section level5">
<h5>MANOVA TESTING</h5>
<pre class="r"><code>library(mvtnorm); library(ggplot2);library(dplyr); library(tidyverse); library(lmtest)
#install.packages(&quot;glmnet&quot;)
library(glmnet)
meteorites &lt;- readr::read_csv(&quot;https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-11/meteorites.csv&quot;) %&gt;% na.omit
ggplot(meteorites, aes(x = year, y = mass)) +  geom_point(alpha = .5) + geom_density_2d(h=2) + coord_fixed() + facet_wrap(~fall)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-1-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>man1&lt;-manova(cbind(year,mass)~fall, data=meteorites)
summary(man1)</code></pre>
<pre><code>##              Df Pillai approx F num Df den Df    Pr(&gt;F)    
## fall          1 0.2588   6653.7      2  38112 &lt; 2.2e-16 ***
## Residuals 38113                                            
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1)</code></pre>
<pre><code>##  Response year :
##                Df   Sum Sq Mean Sq F value    Pr(&gt;F)    
## fall            1  6328187 6328187   13110 &lt; 2.2e-16 ***
## Residuals   38113 18396951     483                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response mass :
##                Df     Sum Sq    Mean Sq F value  Pr(&gt;F)  
## fall            1 1.1153e+12 1.1153e+12  2.8219 0.09299 .
## Residuals   38113 1.5063e+16 3.9522e+11                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>meteorites %&gt;% group_by(fall) %&gt;% summarize(mean(year), mean(mass))</code></pre>
<pre><code>## # A tibble: 2 x 3
##   fall  `mean(year)` `mean(mass)`
##   &lt;chr&gt;        &lt;dbl&gt;        &lt;dbl&gt;
## 1 Fell         1914.       47506.
## 2 Found        1992.       14684.</code></pre>
<pre class="r"><code>pairwise.t.test(meteorites$year,meteorites$fall, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  meteorites$year and meteorites$fall 
## 
##       Fell  
## Found &lt;2e-16
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(meteorites$mass,meteorites$fall, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  meteorites$mass and meteorites$fall 
## 
##       Fell 
## Found 0.093
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>1 - (0.95^4) # probability of at least one type I error</code></pre>
<pre><code>## [1] 0.1854938</code></pre>
<pre class="r"><code>0.05/7 #Boneferroni correction</code></pre>
<pre><code>## [1] 0.007142857</code></pre>
<p>The one-way multivariate analysis of variance (MANOVA) was conducted to determine the effect of meteorite type (fell or found) on two variables (year and mass). Based on the MANOVA, there were significant difference found between the two meteorite types, Pillai trace= 0.2588, pseudoF (2,38112)= 6653.7, p &lt;0.0001. Univariate analyses of variance for each variable were conducted as follow-up tests to the MANOVA. The univerate ANOVAs for year was significant with p &lt; 0.0001. The univerate ANOVAs for mass was not significant with p &gt; 0.05. The found and fell groups differ based on year, but not mass.</p>
<p>I performed 1 MANOVA, 2 ANOVAs, and 4 t tests, so α = 0.05/7 as significance level. The probability of at least one type I error, unadjusted, is 0.1854938. The Bonferroni corrected significance level is 0.007142857. The year is still significant, while the mass is not. There are several assumptions including multivariate normality, equal covariance between two dependent variables, linear relationships among variables, no extreme univariate or multivariate outliers, and no multicollinearity. It is likely that not all assumptions are met.</p>
</div>
<div id="randomization-test" class="section level5">
<h5>Randomization Test</h5>
<pre class="r"><code>fall_type&lt;-meteorites %&gt;% select(fall, mass)
head(fall_type)</code></pre>
<pre><code>## # A tibble: 6 x 2
##   fall    mass
##   &lt;chr&gt;  &lt;dbl&gt;
## 1 Fell      21
## 2 Fell     720
## 3 Fell  107000
## 4 Fell    1914
## 5 Fell     780
## 6 Fell    4239</code></pre>
<pre class="r"><code>ggplot(fall_type,aes(mass,fill=fall))+geom_histogram(bins=6.5)+facet_wrap(~fall,ncol=2)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-2-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>fall_type %&gt;% group_by(fall) %&gt;% summarize(means=mean(mass)) %&gt;% summarize(mean_diff=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   mean_diff
##       &lt;dbl&gt;
## 1   -32823.</code></pre>
<pre class="r"><code>rand_dist&lt;-vector() 
for(i in 1:5000){
  new&lt;-data.frame(mass=sample(fall_type$mass),fall_type=fall_type$fall)
  rand_dist[i]&lt;-mean(new[new$fall_type==&quot;Fell&quot;,]$mass)
  mean(new[new$condition==&quot;Found&quot;,]$mass)}

{hist(rand_dist, main = &quot;&quot;, ylab = &quot;&quot;); abline(v=-32822.54, col=&quot;red&quot;)}</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-2-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>mean(rand_dist&gt;32822.54)*2 #p-value</code></pre>
<pre><code>## [1] 0.254</code></pre>
<p>Null Hypothesis: Mean mass is the same for fall_type (fell vs. found) meteorites.
Alternative Hypothesis: Mean mass is not the same for fall_type (fell vs. found) meteorites.
Based on this test, we fail to reject the null hypothesis (p&gt;0.05). There is a probability of 0.2796 to get a mean difference if the outcome data was split into every possible random grouping.</p>
</div>
<div id="linear-regression" class="section level5">
<h5>Linear Regression</h5>
<pre class="r"><code>meteorites$lat_c&lt;-meteorites$lat-mean(meteorites$lat)
meteorites$long_c&lt;-meteorites$long-mean(meteorites$long)

fit1&lt;-lm(mass~lat_c+long_c, data = meteorites)

summary(fit1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = mass ~ lat_c + long_c, data = meteorites)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
##   -62460   -32444    -6083     2292 59975208 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 15600.71    3218.86   4.847 1.26e-06 ***
## lat_c         341.81      86.59   3.947 7.92e-05 ***
## long_c        -54.17      49.50  -1.094    0.274    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 628400 on 38112 degrees of freedom
## Multiple R-squared:  0.0008861,  Adjusted R-squared:  0.0008336 
## F-statistic:  16.9 on 2 and 38112 DF,  p-value: 4.611e-08</code></pre>
<pre class="r"><code>ggplot(meteorites,aes(y=long_c,x=lat_c,color=mass))+geom_point()+stat_smooth(method=&quot;lm&quot;,se=FALSE)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(meteorites,aes(y=mass,x=long_c))+geom_point()+stat_smooth(method=&quot;lm&quot;,se=FALSE)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(meteorites,aes(y=mass,x=lat_c))+geom_point()+stat_smooth(method=&quot;lm&quot;,se=FALSE)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>qqnorm(meteorites$lat_c)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-4.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>qqnorm(meteorites$long_c)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-5.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>shapiro.test(head(meteorites$lat_c))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  head(meteorites$lat_c)
## W = 0.82491, p-value = 0.09727</code></pre>
<pre class="r"><code>shapiro.test(head(meteorites$long_c))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  head(meteorites$long_c)
## W = 0.92664, p-value = 0.5544</code></pre>
<pre class="r"><code>bptest(fit1) #testing heteroskedasticity assumption</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit1
## BP = 10.219, df = 2, p-value = 0.00604</code></pre>
<pre class="r"><code>library(sandwich)
coeftest(fit1, vcov = vcovHC(fit1)) </code></pre>
<pre><code>## 
## t test of coefficients:
## 
##              Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept) 15600.706   3219.115  4.8463 1.263e-06 ***
## lat_c         341.807    114.302  2.9904  0.002788 ** 
## long_c        -54.173     57.577 -0.9409  0.346772    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>summary(fit1)$r.sq</code></pre>
<pre><code>## [1] 0.0008860555</code></pre>
<pre class="r"><code>fit5&lt;-lm(mass~lat, data = meteorites) #main effects of lat
summary(fit5)</code></pre>
<pre><code>## 
## Call:
## lm(formula = mass ~ lat, data = meteorites)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
##   -59091   -31352    -2877     -691 59976434 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 31361.18    4240.30   7.396 1.43e-13 ***
## lat           398.03      69.71   5.710 1.14e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 628400 on 38113 degrees of freedom
## Multiple R-squared:  0.0008547,  Adjusted R-squared:  0.0008284 
## F-statistic:  32.6 on 1 and 38113 DF,  p-value: 1.14e-08</code></pre>
<pre class="r"><code>fit6&lt;-lm(mass~long, data = meteorites) #main effects of long
summary(fit6)</code></pre>
<pre><code>## 
## Call:
## lm(formula = mass ~ long, data = meteorites)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
##   -54155   -25128   -16703     1049 59977019 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 26028.56    4041.79   6.440 1.21e-10 ***
## long         -170.09      39.86  -4.267 1.98e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 628500 on 38113 degrees of freedom
## Multiple R-squared:  0.0004776,  Adjusted R-squared:  0.0004514 
## F-statistic: 18.21 on 1 and 38113 DF,  p-value: 1.982e-05</code></pre>
<pre class="r"><code>#install.packages(&quot;interactions&quot;)
library(interactions)
interact_plot(fit1,lat_c,long_c) #interaction plot </code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-6.png" width="768" style="display: block; margin: auto;" /></p>
<p>For every one unit increase in mass, the latitude increases by 341.81 units and the longitude decreases by 54.17 units. The linearity assumption is violated based on the ggplot. There does seem to be normality based on the q-q plots. From the Shapiro-Wilk, the p-value &gt; 0.05 implying that the distribution of the data are not significantly different from normal distribution. In other words, we can assume the normality. Based on the Breusch-Pagan test, the p-Value &lt; 0.05 indicates that the null hypothesis can not be rejected and therefore heterscedasticity does not exists. With the robust standard errors, both the t values and the p-values decreased. The proportion of the variation in the outcome explained by this model is 0.0008860555.</p>
</div>
<div id="regression-with-interaction" class="section level5">
<h5>Regression with Interaction</h5>
<pre class="r"><code>fit2&lt;-lm(mass~lat*long, data = meteorites)
boot_sd&lt;-meteorites[sample(nrow(meteorites),replace=TRUE),]

samp_distn&lt;-replicate(1000, {
  boot_sd&lt;-meteorites[sample(nrow(meteorites),replace=TRUE),]
  fit3&lt;-lm(mass~lat*long,data=boot_sd)
  coef(fit3)
  })

samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept)      lat     long lat:long
## 1     6974.63 136.5902 168.8288  2.27977</code></pre>
<pre class="r"><code>summary(fit2) #uncorrected SEs</code></pre>
<pre><code>## 
## Call:
## lm(formula = mass ~ lat * long, data = meteorites)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
##  -110485   -31611    -2297     -801 59978794 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 31859.535   4362.585   7.303 2.87e-13 ***
## lat           406.072     90.090   4.507 6.58e-06 ***
## long         -202.389     75.781  -2.671  0.00757 ** 
## lat:long       -2.635      1.020  -2.583  0.00980 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 628400 on 38111 degrees of freedom
## Multiple R-squared:  0.001061,   Adjusted R-squared:  0.0009823 
## F-statistic: 13.49 on 3 and 38111 DF,  p-value: 8.534e-09</code></pre>
<pre class="r"><code>coeftest(fit2, vcov = vcovHC(fit2)) #corrected SEs</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##               Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept) 31859.5354  6961.2313  4.5767 4.738e-06 ***
## lat           406.0724   138.6713  2.9283   0.00341 ** 
## long         -202.3887   171.7358 -1.1785   0.23861    
## lat:long       -2.6353     2.3300 -1.1310   0.25805    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The p-values for the corrected SEs are higher than the p-values of the uncorrected ones. Additionally the Std. Errors for the corrected SEs are also higher than the uncorrected ones.</p>
</div>
<div id="logistic-regression" class="section level5">
<h5>Logistic Regression</h5>
<pre class="r"><code>meteorites$y&lt;-ifelse(meteorites$fall==&quot;Found&quot;,1,0)
fit3&lt;-glm(y~year+name_type, data = meteorites, family=&quot;binomial&quot;)
coeftest(fit3)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##                   Estimate  Std. Error z value Pr(&gt;|z|)    
## (Intercept)    -6.8207e+01  1.9097e+02 -0.3572   0.7210    
## year            4.1327e-02  7.8972e-04 52.3306   &lt;2e-16 ***
## name_typeValid -9.6912e+00  1.9096e+02 -0.0507   0.9595    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fit3))</code></pre>
<pre><code>##    (Intercept)           year name_typeValid 
##   2.388212e-30   1.042193e+00   6.182406e-05</code></pre>
<pre class="r"><code>meteorites$prob&lt;-predict(fit3,type=&quot;response&quot;) #save predicted probabilities
table(predict= as.numeric(meteorites$prob&gt;0.5), truth = meteorites$y) %&gt;% addmargins()</code></pre>
<pre><code>##        truth
## predict     0     1   Sum
##     0     313   200   513
##     1     752 36850 37602
##     Sum  1065 37050 38115</code></pre>
<pre class="r"><code>36850/37050 #TPR</code></pre>
<pre><code>## [1] 0.9946019</code></pre>
<pre class="r"><code>313/1065 #TNR</code></pre>
<pre><code>## [1] 0.2938967</code></pre>
<pre class="r"><code>36850/37602 #PPV</code></pre>
<pre><code>## [1] 0.9800011</code></pre>
<pre class="r"><code>pca1&lt;-princomp(meteorites[c(&#39;year&#39;,&#39;mass&#39;)])
meteorites$predictor&lt;-pca1$scores[,1]
ggplot(meteorites, aes(predictor,prob))+geom_point(aes(color=fall),alpha=.5,size=3) </code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-5-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(meteorites)+geom_density(aes(prob,fill=y))+xlab(&quot;logit&quot;)# plot density of log-odds (logit) by your binary outcome variable</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-5-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>sens&lt;-function(p,data=meteorites, y=y) mean(meteorites[meteorites$y==1,]$prob&gt;p)
spec&lt;-function(p,data=meteorites, y=y) mean(meteorites[meteorites$y==0,]$prob&lt;p)

sensitivity&lt;-sapply(seq(0,1,.01),sens,meteorites)
specificity&lt;-sapply(seq(0,1,.01),spec,meteorites)
ROC1&lt;-data.frame(sensitivity,specificity,cutoff=seq(0,1,.01)) 
ROC1%&gt;%gather(key,rate,-cutoff)%&gt;%ggplot(aes(cutoff,rate,color=key))+geom_path()+  geom_vline(xintercept=c(.1,.5),lty=2,color=&quot;gray50&quot;)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-5-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ROC1$TPR&lt;-sensitivity
ROC1$FPR&lt;-1-specificity
ROC1%&gt;%ggplot(aes(FPR,TPR))+geom_path(size=1.5)+geom_segment(aes(x=0,y=0,xend=1,yend=1),lty=2)+  scale_x_continuous(limits = c(0,1))</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-5-4.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(plotROC)
ROCplot&lt;-ggplot(meteorites)+geom_roc(aes(d=y,m=predictor), n.cuts=0) 
calc_auc(ROCplot) #AUC</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.8979831</code></pre>
<pre class="r"><code>class_diag&lt;-function(probs,truth){
  
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]

  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,auc)
}

k=10
data1&lt;-meteorites[sample(nrow(meteorites)),]
folds&lt;-cut(seq(1:nrow(meteorites)),breaks=k,labels=F)

diags&lt;-NULL 
for(i in 1:k){
  train&lt;-data1[folds!=i,]   
  test&lt;-data1[folds==i,]
  truth&lt;-test$y
  fit&lt;-glm(y~year+name_type,data=train,family=&quot;binomial&quot;)
  probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
  diags&lt;-rbind(diags,class_diag(probs,truth)) 
}

apply(diags,2,mean)</code></pre>
<pre><code>##       acc      sens      spec       ppv       auc 
## 0.9750228 0.9946018 0.2941791 0.9800003 0.8946289</code></pre>
<p>Based on the logistic regression, the odds of being ‘found’ is 1.633141e-35 and the odds of being ‘found’ increases exponentially by 1.042 as the year increases. The odds of being a valid ‘name_type’ is 6.182405e-05.</p>
<p>The sensitivity, or true positive rate (TPR), is 0.9946019 and the specificity, or true negative rate (TNR), is 0.2938967. This means that this model is fairly good at detecting the probability of a ‘found’ meteorite actually being found. However, it is not as good as detecting meteorites that ‘fell’. The precision (PPV) is 0.9800011, which is the proportion of those classified as ‘found’ actually being found.</p>
<p>The ROC curve let’s us visualize trade-off between sensitivity and specificity. The AUC is 0.8979831, which means that this model is good at predicting if ‘found’. The rule of thumb for AUC is 0.8-0.9 is good. After the fold classification diagnositics (I used k=500 because I had a huge dataset.), the acc (accuracy) is 0.9700408, the sens is 0.9927454, the spec is 0.2422619, and the ppv is 0.9767507. The sensitivity went down slightly and the AUC decreased as well.</p>
</div>
<div id="lasso-regression" class="section level5">
<h5>LASSO Regression</h5>
<pre class="r"><code>fit8&lt;-glm(y~name_type+mass+lat+long, data = meteorites, family = binomial) #While I did want to use all the rest of the variables as predictors, the dataset is so large that I limited the variables
x&lt;-model.matrix(fit8)
y&lt;-as.matrix(meteorites$y)
cv&lt;-cv.glmnet(x,y,family = &#39;binomial&#39;)
lasso1&lt;-glmnet(x,y,family = &#39;binomial&#39;,lambda=cv$lambda.1se)
coef(lasso1)</code></pre>
<pre><code>## 6 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                          s0
## (Intercept)     4.626924847
## (Intercept)     .          
## name_typeValid -0.968619234
## mass            .          
## lat            -0.050186572
## long           -0.004033743</code></pre>
<pre class="r"><code>prob&lt;-predict(lasso1, newx = x, type = &quot;response&quot;)
class_diag(prob, meteorites$y)</code></pre>
<pre><code>##         acc      sens        spec       ppv       auc
## 1 0.9716647 0.9995412 0.001877934 0.9720968 0.9207447</code></pre>
<pre class="r"><code>k=10
meteorites$valid&lt;-x[,&quot;name_typeValid&quot;]
data2&lt;-meteorites[sample(nrow(meteorites)),]
folds2&lt;-cut(seq(1:nrow(meteorites)),breaks=k,labels=F)

diags&lt;-NULL 
for(i in 1:k){
  train&lt;-data2[folds2!=i,]   
  test&lt;-data2[folds2==i,]
  truth&lt;-test$y
  fit&lt;-glm(y~valid+lat+long,data=train,family=&quot;binomial&quot;)
  probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
  diags&lt;-rbind(diags,class_diag(probs,truth)) 
}

apply(diags,2,mean)</code></pre>
<pre><code>##        acc       sens       spec        ppv        auc 
## 0.97121872 0.99746300 0.05892524 0.97357737 0.91826080</code></pre>
<pre class="r"><code>summary(fit8)</code></pre>
<pre><code>## 
## Call:
## glm(formula = y ~ name_type + mass + lat + long, family = binomial, 
##     data = meteorites)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.9959   0.0166   0.0216   0.1680   2.1423  
## 
## Coefficients:
##                  Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     1.857e+01  1.835e+02   0.101    0.919    
## name_typeValid -1.431e+01  1.835e+02  -0.078    0.938    
## mass            3.877e-08  3.535e-08   1.097    0.273    
## lat            -7.153e-02  2.133e-03 -33.542   &lt;2e-16 ***
## long           -8.659e-03  5.995e-04 -14.445   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 9720.3  on 38114  degrees of freedom
## Residual deviance: 6513.7  on 38110  degrees of freedom
## AIC: 6523.7
## 
## Number of Fisher Scoring iterations: 13</code></pre>
<p>The variables ‘name_type’, ‘lat’, and ‘long’ are retained. The acc ,sens, spec, and ppv are the lower when compared to the logistic regression. However, the AUC is higher when compared to the logistic regression above. The residual standard error is 6513.7.</p>
<pre><code>## R version 3.6.1 (2019-07-05)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 17134)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=English_United States.1252 
## [2] LC_CTYPE=English_United States.1252   
## [3] LC_MONETARY=English_United States.1252
## [4] LC_NUMERIC=C                          
## [5] LC_TIME=English_United States.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] plotROC_2.2.1      interactions_1.1.1 sandwich_2.5-1    
##  [4] glmnet_3.0-1       Matrix_1.2-17      lmtest_0.9-37     
##  [7] zoo_1.8-6          forcats_0.4.0      stringr_1.4.0     
## [10] purrr_0.3.2        readr_1.3.1        tidyr_1.0.0       
## [13] tibble_2.1.3       tidyverse_1.2.1    dplyr_0.8.3       
## [16] ggplot2_3.2.1      mvtnorm_1.0-11     knitr_1.25        
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_1.0.2       lubridate_1.7.4  lattice_0.20-38  assertthat_0.2.1
##  [5] zeallot_0.1.0    digest_0.6.21    foreach_1.4.7    utf8_1.1.4      
##  [9] plyr_1.8.4       R6_2.4.0         cellranger_1.1.0 backports_1.1.5 
## [13] evaluate_0.14    httr_1.4.1       blogdown_0.17    pillar_1.4.2    
## [17] rlang_0.4.0      lazyeval_0.2.2   curl_4.2         readxl_1.3.1    
## [21] rstudioapi_0.10  rmarkdown_1.16   labeling_0.3     pander_0.6.3    
## [25] munsell_0.5.0    broom_0.5.2      compiler_3.6.1   modelr_0.1.5    
## [29] xfun_0.10        pkgconfig_2.0.3  shape_1.4.4      htmltools_0.3.6 
## [33] tidyselect_0.2.5 bookdown_0.16    codetools_0.2-16 fansi_0.4.0     
## [37] crayon_1.3.4     withr_2.1.2      MASS_7.3-51.4    grid_3.6.1      
## [41] nlme_3.1-140     jsonlite_1.6     gtable_0.3.0     lifecycle_0.1.0 
## [45] magrittr_1.5     scales_1.0.0     cli_1.1.0        stringi_1.4.3   
## [49] xml2_1.2.2       ellipsis_0.3.0   jtools_2.0.1     vctrs_0.2.0     
## [53] generics_0.0.2   iterators_1.0.12 tools_3.6.1      glue_1.3.1      
## [57] hms_0.5.1        yaml_2.2.0       colorspace_1.4-1 rvest_0.3.4     
## [61] haven_2.1.1</code></pre>
<pre><code>## [1] &quot;2019-12-06 23:46:21 CST&quot;</code></pre>
<pre><code>##           sysname           release           version          nodename 
##         &quot;Windows&quot;          &quot;10 x64&quot;     &quot;build 17134&quot; &quot;WINDOWS-01O3VTU&quot; 
##           machine             login              user    effective_user 
##          &quot;x86-64&quot;               &quot;A&quot;               &quot;A&quot;               &quot;A&quot;</code></pre>
</div>
</div>
</div>
</div>

</main>

        <footer>
            <p class="copyright text-muted">© All rights reserved. Powered by <a href="https://gohugo.io">Hugo</a> and <a href="https://github.com/calintat/minimal">Minimal</a>.</p>
        </footer>

        

        
    </body>

</html>

