baseURL = "/"
languageCode = "en-us"
title = "SDS 348 Projects"
theme = "minimal"
disqusShortname = "username"
googleAnalytics = ""

[params]
    author = "Ann Wang"
    description = "Links to the Projects are provided in the projects tab."
    githubUsername = "#"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "https://annwang.netlify.com/"
    name = "Resume Page"
    weight = 2

[[menu.main]]
    url = "/Project1/"
    name = "Project1"
    weight = 3
    
[[menu.main]]
    url = "/Project2/"
    name = "Project 2"
    weight = 4

# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "linkedin"
    weight = 4

