baseURL = "/"
languageCode = "en-us"
title = "SDS 348 Projects"
theme = "minimal"
disqusShortname = "username"
googleAnalytics = ""

[params]
    author = "Ann Wang"
    description = " The Resume Page will link you to the original page. Links to the Projects are provided in the tabs above."
    githubUsername = "#"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Roboto Slab" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "https://annwang.netlify.com/"
    name = "Resume Page"
    weight = 2

[[menu.main]]
    url = "/Project1/"
    name = "Project 1"
    weight = 3
    
[[menu.main]]
    url = "/Project2/"
    name = "Project 2"
    weight = 4
    
[[menu.main]]
    url = "/hugoisforlovers/"
    name = "Blog Post"
    weight = 5

# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:ann.wang@utexas.edu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/ann-DIY/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/ann-wang-aw29983/"
    name = "linkedin"
    weight = 3

